services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - lab-observabilidade

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    networks:
      - lab-observabilidade

  service-a:
    image: registry.gitlab.com/devopsrt71/container-images/golang.1.22.8-arm64
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - LO_PORT=8080
      - SB_HOST=service-b
      - SB_PORT=8080
    volumes:
      - ../lab-observabilidade-service-a:/app
    command: ["sleep", "infinity"]
    # command: >
    #   sh -c "
    #   cd /app && go mod tidy &&
    #   GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-a ./cmd/api/service-a/main.go &&
    #   ./build/service-a"
    depends_on:
      - zipkin
    networks:
      - lab-observabilidade

  service-b:
    image: registry.gitlab.com/devopsrt71/container-images/golang.1.22.8-arm64
    container_name: service-b
    ports:
      - "8081:8080"
    environment:
      - LO_PORT=8080
      - WEATHER_TOKEN=d5a4cb1d02924fda961141910240111
    volumes:
      - ../lab-observabilidade-service-b:/app
    command: ["sleep", "infinity"]
    # command: >
    #   sh -c "
    #   cd /app && go mod tidy &&
    #   GOOS=linux CGO_ENABLED=0 go build -ldflags='-w -s' -o ./build/service-b ./cmd/api/service-b/main.go &&
    #   ./build/service-b"
    depends_on:
      - zipkin
    networks:
      - lab-observabilidade

  pkg:
    image: registry.gitlab.com/devopsrt71/container-images/golang.1.22.8-arm64
    container_name: pkg
    volumes:
      - ./:/app
    command: ["sleep", "infinity"]
    networks:
      - lab-observabilidade

networks:
  lab-observabilidade:
    driver: bridge
